name: Build Docker-Image

on:
  push:
    branches:
      - 'main'
    tags: [ '*.*.*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PHP_CS_FIXER_VERSION: '3.54.0'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4

      -
        name: Setup Docker buildx
        uses: docker/setup-buildx-action@a530e948adbeb357dbca95a7f8845d385edf4438

      -
        name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Extract Docker metadata
        id: meta-action
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      -
        name: Build and push Docker image
        id: build-and-push-action
        uses: docker/build-push-action@31159d49c0d4756269a0940a750801a1ea5d7003
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            PHP_CS_FIXER_VERSION=${{ env.PHP_CS_FIXER_VERSION }}
          push: true
          platforms: "linux/amd64,linux/arm64"
          tags: ${{ steps.meta-action.outputs.tags }}
          labels: ${{ steps.meta-action.outputs.labels }}
          sbom: false
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
